src/IO.App/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IO.App.Extensions;
using Microsoft.AspNetCore.Http;

namespace IO.App.ViewModels
{
    public class ProductViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "{0} - Required field")]
        [DisplayName("Provider")]
        public Guid ProviderId { get; set; }

        [Required(ErrorMessage = "{0} - Required field")]
        [StringLength(200, ErrorMessage = "The field {0} must be between {2} e {1} characteres", MinimumLength = 2)]
        public string Name { get; set; }

        [Required(ErrorMessage = "{0} - Required field")]
        [StringLength(1000, ErrorMessage = "The field {0} must be between {2} e {1} characteres", MinimumLength = 2)]
        public string Description { get; set; }

        [DisplayName("Image of product")]
        public IFormFile ImageUpload { get; set; }

        public string Image { get; set; }

        [Currency]
        [Required(ErrorMessage = "{0} - Required field")]
        public decimal Value { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DateRegister { get; set; }

        [DisplayName("Activ?")]
        public bool Activ { get; set; }

        /* Entity Framework Relations */
        public ProviderViewModel Provider { get; set; }

        public IEnumerable<ProviderViewModel> Providers { get; set; }
    }
}

src/IO.App/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using IO.App.ViewModels;
using AutoMapper;
using IO.Business.Interfaces;
using IO.Business.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using IO.App.Extensions;

namespace IO.App.Controllers
{
    [Authorize]
    public class ProductsController : BaseController
    {
        private readonly IProductRepository _productRepository;
        private readonly IProviderRepository _providerRepository;
        private readonly IProductService _productService;
        private readonly IMapper _mapper;

        public ProductsController(IProductRepository productRepository,
                                  IProviderRepository providerRepository,
                                  IProductService productService,
                                  IMapper mapper,
                                  INotifier notifier) : base(notifier)
        {
            _productRepository = productRepository;
            _providerRepository = providerRepository;
            _productService = productService;
            _mapper = mapper;
        }

        [AllowAnonymous]
        [Route("list-products")]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<ProductViewModel>>(await _productRepository.GetProductsProviders()));
        }

        [AllowAnonymous]
        [Route("details-product/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var productViewModel = await GetProduct(id);

            if (productViewModel == null)  return NotFound();

            return View(productViewModel);
        }

        [ClaimsAuthorize("Product","Add")]
        [Route("new-product")]
        public async Task<IActionResult> Create()
        {
            var productViewModel = await PopularProviders(new ProductViewModel());

            return View(productViewModel);
        }

        [ClaimsAuthorize("Product", "Add")]
        [Route("new-product")]
        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            productViewModel = await PopularProviders(productViewModel);

            if (!ModelState.IsValid) return View(productViewModel);

            var imgPrefix = Guid.NewGuid() + "_";

            if(! await UploadArchive(productViewModel.ImageUpload, imgPrefix))
            {
                return View(productViewModel);
            }

            productViewModel.Image = imgPrefix + productViewModel.ImageUpload.FileName;

            await _productService.Add(_mapper.Map<Product>(productViewModel));

            if (!ValidOperation()) return View(productViewModel);

            TempData["Success"] = "Product successfully created.";

            return RedirectToAction("Index");

        }

        [ClaimsAuthorize("Product", "Edit")]
        [Route("edition-product/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var productViewModel = await GetProduct(id);

            if (productViewModel == null) return NotFound();

            return View(productViewModel);
        }

        [ClaimsAuthorize("Product", "Edit")]
        [Route("edition-product/{id:guid}")]
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, ProductViewModel productViewModel)
        {
            if (id != productViewModel.Id) return NotFound();

            var productUpdate = await GetProduct(id);
            productViewModel.Provider = productUpdate.Provider;
            productViewModel.Image = productUpdate.Image;
            if (!ModelState.IsValid) return View(productViewModel);

            if (productViewModel.ImageUpload != null)
            {
                var imgPrefix = Guid.NewGuid() + "_";
                if (!await UploadArchive(productViewModel.ImageUpload, imgPrefix))
                {
                    return View(productViewModel);
                }

                productUpdate.Image = imgPrefix + productViewModel.ImageUpload.FileName;
            }

            productUpdate.Name = productViewModel.Name;
            productUpdate.Description = productViewModel.Description;
            productUpdate.Value = productViewModel.Value;
            productUpdate.Activ = productViewModel.Activ;

            await _productService.Update(_mapper.Map<Product>(productUpdate));

            if (!ValidOperation()) return View(productViewModel);

            return RedirectToAction("Index");
        }

        [ClaimsAuthorize("Product", "Delete")]
        [Route("delete-product/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var product = await GetProduct(id);

            if (product == null) return NotFound();

            return View(product);
        }

        [ClaimsAuthorize("Product", "Delete")]
        [Route("delete-product/{id:guid}")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var product = await GetProduct(id);

            if(product == null) return NotFound();

            await _productService.Remove(id);

            if (!ValidOperation()) return View(product);

            TempData["Success"] = "Product successfully deleted.";

            return RedirectToAction(nameof(Index));
        }

        private async Task<ProductViewModel> GetProduct(Guid id)
        {
            var product = _mapper.Map<ProductViewModel>(await _productRepository.GetProductProvider(id));
            product.Providers = _mapper.Map<IEnumerable<ProviderViewModel>>(await _providerRepository.SearchAll());
            return product;
        }

        private async Task<ProductViewModel> PopularProviders(ProductViewModel product)
        {
            product.Providers = _mapper.Map<IEnumerable<ProviderViewModel>>(await _providerRepository.SearchAll());
            return product;
        }

        private async Task<bool> UploadArchive(IFormFile archive, string imgPrefix)
        {
            if (archive.Length <= 0) return false;

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", imgPrefix + archive.FileName);

            if (System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "A file with this name already exists!");
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await archive.CopyToAsync(stream);
            }

            return true;
        }
    }
}

src/IO.App/Extensions/SummaryViewComponent.cs
using System;
using System.Threading.Tasks;
using IO.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace IO.App.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotifier _notifier;

        public SummaryViewComponent(INotifier notifier)
        {
            _notifier = notifier;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacions = await Task.FromResult(_notifier.GetNotifications());

            notificacions.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Message));

            return View();
        }
    }
}

src/IO.App/Views/Products/Create.cshtml
@model IO.App.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "New Product";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-5">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProviderId" class="control-label"></label>
                <select asp-for="ProviderId" class="form-control" asp-items="@(new SelectList(Model.Providers, "Id", "Name"))">
                    <option>-- select provider --</option>
                </select>
                <span asp-validation-for="ProviderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="ImageUpload" asp-for="ImageUpload">
                    <label data-browse="Search" class="custom-file-label" for="ImageUpload"></label>
                    <label style="display: none" id="img_nome"></label>
                </div>
                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activ" /> @Html.DisplayNameFor(model => model.Activ)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Insert" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Back</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
        $("#ImageUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });

        $("#ImageUpload").attr("data-val", "true");
        $("#ImageUpload").attr("data-val-required", "Required field");
</script>
}

src/IO.App/Views/Products/Delete.cshtml
@model IO.App.ViewModels.ProductViewModel

@{ ViewData["Title"] = "Delete " + Model.Name; }

<h4 style="padding-top: 50px">@ViewData["Title"] </h4>

<h5>Are you sure you want to delete this?</h5>

<div class="row">
    <div class="col-md-4">
        <img src="~/images/@Model.Image" alt="@Model.Image" style="width: 300px; height: 428px" />
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Provider)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Provider.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Value)
            </dt>
            <dd class="col-sm-10">
                @Model.Value.ToString("C")
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Activ)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Activ)
            </dd>
        </dl>
        <div>
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a class="btn btn-info" href="javascript:window.history.back();">Back</a>
            </form>
        </div>
    </div>
</div>

src/IO.App/Views/Products/Details.cshtml
@model IO.App.ViewModels.ProductViewModel

@{ ViewData["Title"] = "Details of Product - " + Model.Name; }

<h4 style="padding-top: 50px">@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <img src="~/images/@Model.Image" alt="@Model.Image" style="width: 300px; height: 428px" />
    </div>
    <div class="col-md-6">
        <dl>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Provider)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Provider.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Value)
            </dt>
            <dd class="col-sm-10">
                @Model.Value.ToString("C")
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Activ)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Activ)
            </dd>
        </dl>

        <div>
            <a supress-by-claim-name="Product" supress-by-claim-value="Edit" class="btn btn-dark" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
            <a class="btn btn-info" href="javascript:window.history.back();">Back</a>
        </div>
    </div>
</div>


src/IO.App/Views/Products/Edit.cshtml
@model IO.App.ViewModels.ProductViewModel

@{ ViewData["Title"] = "Edit " + Model.Name; }

<h4 style="padding-top: 30px">@ViewData["Title"] </h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="ProviderId" class="control-label"></label><br />
                <label><b>@Model.Provider.Name</b></label>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Current Image</label><br />
                <img src="~/images/@Model.Image" alt="@Model.Image" style="width: 70px; height: 100px" />
            </div>

            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="ImagemUpload" asp-for="ImageUpload">
                    <label data-browse="Search" style="width: 400px" class="custom-file-label" for="ImageUpload"></label>
                    <label style="display: none" id="img_nome"></label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activ" /> @Html.DisplayNameFor(model => model.Activ)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-info" href="javascript:window.history.back();">Back</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
        $("#ImagemUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });
</script>
}

src/IO.App/Views/Products/Index.cshtml
@model IEnumerable<IO.App.ViewModels.ProductViewModel>

@{
    ViewData["Title"] = "List Products";
}

<h1>@ViewData["Title"]</h1>
<hr />
<vc:summary></vc:summary>

<p>
    <a class="btn btn-info" asp-action="Create">New Product</a>
</p>

<partial name="_ListProducts" />

src/IO.App/Views/Products/_ListProducts.cshtml
@model IEnumerable<IO.App.ViewModels.ProductViewModel>

<table class="table table-hover">
    <thead class="thead thead-dark">
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Provider)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activ)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="~/images/@item.Image" alt="@item.Image" style="width: 70px; height: 100px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Provider.Name)
            </td>
            <td>
                @item.Value.ToString("C")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activ)
            </td>

            <td class="text-right">
                <a class="btn btn-info" asp-controller="Products" asp-action="Details" asp-route-id="@item.Id"><span class="fa fa-search"></span></a>
                <a class="btn btn-warning" asp-controller="Products" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-pencil-alt"></span></a>
                <a class="btn btn-danger" asp-controller="Products" asp-action="Delete" asp-route-id="@item.Id"><span class="fa fa-trash"></span></a>
            </td>
        </tr>
}
    </tbody>
</table>